---
title: "K-means con la función KMeans_Arma del paquete clusterR"
output: html_notebook
---

```{r}
library(cluster)
library(ClusterR)
```

Cargamos el dataset que vamos a analizar

```{r}
df = read.csv("./online_shoppers_intention.csv")
```

Al igual que en los casos anteriores transformamos las variables categóricas en numéricas:

```{r}
df$Month <- as.numeric(df$Month)
df$Weekend <- as.numeric(df$Weekend)
df$Revenue <- as.numeric(df$Revenue)
df$VisitorType<- as.numeric(df$VisitorType)
```


```{r}
t <- proc.time() # Inicia el cronómetro
```

Finalmente construímos el modelo y obtenemos los cluster a los que pertenecen cada uno de los puntos del data set gracias a la función predict_KMeans() del mismo paquete:

```{r}
#km = KMeans_arma(df, clusters = 3, n_iter = 10, "random_subset")
km = KMeans_arma(df, clusters = 2)
km_cluster = predict_KMeans(df, km)
```


```{r}
proc.time()-t    # Detiene el cronómetro
```

```{r}
object.size(km) + object.size(km_cluster)
```


```{r}
km
```

```{r}
km_cluster
```


```{r}
ss <- silhouette(km_cluster, dist(df))
mean(ss[, 3])
```


```{r}
t <- proc.time() # Inicia el cronómetro
```

```{r}
km = KMeans_arma(df, clusters = 3)
km_cluster = predict_KMeans(df, km)
```


```{r}
proc.time()-t    # Detiene el cronómetro
```

```{r}
km
```

```{r}
km_cluster
```

```{r}
ss <- silhouette(km_cluster, dist(df))
mean(ss[, 3])
```

```{r}
t <- proc.time() # Inicia el cronómetro
```

```{r}
km = KMeans_arma(df, clusters = 4)
km_cluster = predict_KMeans(df, km)
```

```{r}
proc.time()-t    # Detiene el cronómetro
```

```{r}
km
```

```{r}
km_cluster
```

```{r}
ss <- silhouette(km_cluster, dist(df))
mean(ss[, 3])
```